spring:
  application:
    name: PCFSpringBootActuatorDemo
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'